{ lib, ... }:
let
  utils = import ../utils.nix { inherit lib; };
  inherit (utils) string list tuple;
in
rec {

  sampleInput = ''
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
  '';

  expect01 = 21;
  # expect02 = 3263827;
  # expectReal01 = 5873191732773;
  # expectReal02 = 11386445308378;

  input = builtins.readFile ./input/day07.txt;

  parseInput = str: str;

  part01 = input: input |> parseInput;

  part02 = input: input |> parseInput;

}
